### ISSUE TITLE
Remove unnecessary & in MultiMenu CSS

### ISSUE THREAD

**Issue by KaiMagnusMueller** [KaiMagnusMueller/figmakit-plugin-ui#41]
```css
:global(:has(svg)) {
	padding: 0;
}

```

Remove & before :has and ensure CSS is still properly scoped
